# Generated by Django 3.2.7 on 2022-01-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='slug',
        ),
    ]
