# Generated by Django 3.2.9 on 2021-12-30 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20211230_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='pro',
            new_name='product',
        ),
    ]
