# Generated by Django 3.2.7 on 2022-01-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_product_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile_picture',
        ),
    ]
