# Generated by Django 3.2.9 on 2021-12-30 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_pro_wishlist_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='cart',
        ),
    ]
